volumes:
  fail2ban_data:
    name: fail2ban_data

services:
  fail2ban:
    container_name: Fail2Ban
    restart: always
    image: crazymax/fail2ban:latest
    environment: 
      - TZ=Europe/Berlin
      - F2B_DB_PURGE_AGE=30d
      - F2B_LOG_TARGET=/data/fail2ban.log
      - F2B_LOG_LEVEL=INFO
      - F2B_IPTABLES_CHAIN=INPUT
    volumes:
      - fail2ban_data:/data
      - /volumeX/docker/vw-data:/vaultwarden:ro
    network_mode: "host"
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
